import type { Track } from "@/lib/content";

/**
 * Peace of Mind 3 — Lifetime. Guided. Guaranteed.
 *
 * Seeded by refreshPeaceOfMind3() in cms.ts on cms_settings key pom3_v1.
 * visibleToAll so every signed-in role sees it (New Hire, Specialist, MIT, Manager).
 */
export const POM3_TRACK: Track = {
  id: "peace-of-mind-3",
  role: "specialist",
  title: "Peace of Mind 3",
  nav: "Peace of Mind 3",
  href: "/training/peace-of-mind-3",
  image: "/media/classroom-table.jpg",
  audience: "Every position",
  visibleToAll: true,
  summary:
    "After the Maintainer walk. Before the Relaxer. Lifetime, Guided, and Guaranteed — a conversation the client can use. Official wearing guide in the hand. A nod is not understanding.",
  lessons: [
    {
      slug: "start-here",
      title: "Start here",
      minutes: 5,
      kicker: "The standard",
      body: [
        "When: After the Maintainer walk. Before the Relaxer. Every client — not only when they look unsure. Ask about uncertainty. Do not guess it from a look or a gesture.",
        "The performance goal: explain the three points accurately, help the client use the wearing guide, check what they understood, and agree on the next step. Own words. A nod alone does not show understanding.",
        "Lifetime: separate product warranty from the result they hope for. The client can explain what is covered and where to get help.",
        "Guided: put the official wearing guide in their hand. Match supports. Explain a comfortable start. The client can show which support is which, where the starting example lives, and when to stop.",
        "Guaranteed: show the written policy. Explain the conditions plainly. Do not improvise. The client can explain how help works and where to check the refund process.",
        "Run the session in 35 minutes. Mental Aerobics, debrief, model the handoff, two role-plays, then set the next three fittings.",
        "Course boundary: this module teaches reassurance and understanding. Continue the fitting after. If the client needs to stop or leave, respect that and agree on a next step.",
      ],
      takeaway: "A nod is not understanding. The client shows the starting plan and the stop line.",
    },
    {
      slug: "what-do-you-know",
      title: "What do you do next?",
      minutes: 5,
      kicker: "Mental Aerobics",
      body: [
        "Choose the best next response. Then write the question or action. The goal is what you do next — not diagnosing how they feel.",
        "L Lifetime. G Guided. Q Guaranteed. A Ask first. S Safety. R Sequence.",
        "1. \u201cThis is a lot.\u201d — Ask first. \u201cWhich part feels like a lot?\u201d If the answer is price, address price. Do not repeat the schedule.",
        "2. \u201cI cannot remember which support is which.\u201d — Guided. Match each support to its name on the official wearing guide. Have them show you the Strengthener.",
        "3. \u201cIf a support cracks, what do I do?\u201d — Lifetime. Warranty covers breaking, cracking, or splitting — the product. Take it to a Good Feet store with the product and the receipt.",
        "4. \u201cSo I can bring them back next week for a refund?\u201d — Guaranteed. Look at the written conditions together. Do not invent an exception.",
        "5. The client smiles politely but says nothing. — Ask first. \u201cWhat questions do you have so far?\u201d Then one understanding check.",
        "6. The client reaches for their keys. — Ask first. \u201cDo you need to head out?\u201d Offer an agreed next step if they cannot continue.",
        "7. \u201cI have numbness when I wear this.\u201d — Safety. \u201cPlease stop using it. The guide says to discontinue use if pain, numbness, or irritation occurs.\u201d Do not diagnose.",
        "8. The specialist starts the Relaxer demo while the client is still asking about the wearing guide. — Sequence. Set the Relaxer down. Answer. Check understanding. Then ask if they are ready to continue.",
        "A cue is a reason to listen. An ambiguous cue does not tell you which point to repeat.",
      ],
      takeaway: "Ask first when the cue is ambiguous. Then respond to the concern they actually named.",
    },
    {
      slug: "the-map",
      title: "Put the guide to work",
      minutes: 12,
      kicker: "The talk",
      body: [
        "Do not recite the paragraph. Do hit all three points. Then check what they understood.",
        "Open: Before we try the Relaxer, let me explain the support you have behind you — Lifetime, Guided, and Guaranteed. What questions are on your mind so far?",
        "Lifetime: We are not working on today. We are working on the rest of your life. These supports carry a limited lifetime warranty against breaking, cracking, or splitting. That covers the product. It is not a promise of a particular pain outcome. If one fails, take it to a Good Feet store with the product and your receipt.",
        "Guided: There is a lot to remember, so you are not on your own. I want to go over something with you. This is your wearing guide.",
        "Walk the trifold in 30 seconds. Strengthener — start up to 30 minutes, build by how the feet feel. The chart is an example, not a deadline. Maintainer — everyday; after a couple of days it can go two hours to all day, then anytime. Relaxer — anytime, no adjustment. Pointing at that column on the card is allowed. Picking up the physical Relaxer is not — not yet.",
        "Write color, cushion, lifestyle, footwear. Complete specialist name and phone. Hand it. Then: \u201cShow me where you would look for your starting plan, and what would make you stop.\u201d",
        "Guaranteed: Eligible supports have a 90-day client satisfaction policy. Follow the wearing instructions and complete an in-person follow-up during the 60-day adjustment process. If you still do not feel a difference, return to your purchase store by day 90 with your receipt. Let\u2019s look at the full terms together.",
        "Close: If you choose to move forward, I will check in on day three, day ten, and day twenty-one, and put a time on the calendar around day thirty. Pause. Let them answer. Do not pile on. Then — and only then — talk about the Relaxers.",
        "PRACTICE \u00b7 Official wearing guide in the hand before Guided words. Empty hands means you skipped it.",
      ],
      takeaway: "Official trifold. Three columns. Hand it. Then check that they can show start and stop.",
    },
    {
      slug: "practice-the-unexpected",
      title: "Practice the unexpected",
      minutes: 14,
      kicker: "Roleplays",
      body: [
        "Pairs. Two attempts each. 90 seconds for the core explanation, then handle the concern, check understanding, and agree on a next step.",
        "ROLEPLAY \u00b7 Card A — \u201cThis is a lot.\u201d Private detail: they mean the number of supports. Use the actual supports and the guide. Have them identify one.",
        "ROLEPLAY \u00b7 Card B — \u201cI can return these next week, right?\u201d Private detail: they think this is an unrestricted trial. Explain the written conditions. Check understanding.",
        "ROLEPLAY \u00b7 Card C — \u201cThis is a lot.\u201d Private detail: they mean the price. Acknowledge cost. Do not invent a discount or change the guarantee.",
        "ROLEPLAY \u00b7 Card D — Reaches for the keys. Private detail: they leave in two minutes. Check time. Respect the choice. Agree on a continuation.",
        "ROLEPLAY \u00b7 Card E — \u201cSo my pain is gone for life?\u201d Private detail: they confused product coverage with a promised outcome. Separate the two. Do not guarantee relief.",
        "ROLEPLAY \u00b7 Card F — \u201cI tried these and got numbness.\u201d Follow-up visit. Use the stop-use instruction. Do not push continued wear. Do not diagnose.",
        "Round 1: A or B. Round 2: C, D, E, or F. Every learner answers card F out loud in debrief if it was not their scenario.",
        "Name one effective behavior. Name one observable gap. Ask for the repair. Let them retry. Do not lecture the paragraph.",
        "Critical errors: a guaranteed health outcome, materially wrong policy terms, or advice to continue through stop-use symptoms. Correct immediately. A total score cannot cancel a critical error.",
      ],
      takeaway: "Coach the missing point only. Card F is required — stop-use has to stick.",
    },
    {
      slug: "settled-game",
      title: "SETTLED — Don\u2019t Touch the Relaxer",
      minutes: 8,
      kicker: "Game",
      body: [
        "Play the course game before you take this onto the floor. Fear Call first. Then build the talk in order.",
        "GFA \u00b7 Open SETTLED — Don\u2019t Touch the Relaxer and play both rounds.",
        "Paper before Guided words. Pointing at the Relaxer column on the card is allowed. Picking up the physical Relaxer is the trap.",
        "Ask first on \u201cthis is a lot,\u201d a polite smile, and keys. Safety on numbness. Lifetime on \u201cpain gone for life\u201d if you confirm it as a promise.",
      ],
      takeaway: "Don't touch the Relaxer until they are settled.",
    },
    {
      slug: "next-3-fittings",
      title: "Next three fittings",
      minutes: 8,
      kicker: "The habit",
      body: [
        "Classroom does not make this stick. The next three Maintainer walks do.",
        "After every Maintainer walk, run the talk. Before Relaxer. After the client leaves, check: three points accurate, official guide walked, understanding checked, actual concern answered, next step confirmed, talk landed before Relaxer.",
        "Five short rehearsals across the week. Training day: recall the three points. Day 1: guide handoff. Day 3: answer a policy question from the written terms. Day 5: respond to an ambiguous concern. Day 7: a fresh scenario with no model in hand.",
        "One recording — solo or a consenting practice partner, not a live client. Listen for one gap. Bring that observation to the manager.",
        "Pass: three live reflections + one recording + manager heard one client. Every skill at 2. No critical errors. Then you have earned After the Relaxer walk.",
        "A client choosing not to purchase is not a skill failure.",
      ],
      takeaway: "Pass the course on the floor. Not by opening the reading.",
    },
    {
      slug: "manager-policy",
      title: "Keep the promises precise",
      minutes: 8,
      kicker: "Manager + policy",
      body: [
        "Show the written terms. Do not improvise an exception. Confirm product eligibility.",
        "Satisfaction policy: eligible arch supports have a 90-day satisfaction policy. Refund requests follow a 60-day adjustment period, the wearing instructions, and at least one in-person follow-up. If still dissatisfied, return to the original purchase store by day 90 with proof of purchase. Refunds go to the original payment method, without a restocking fee. A refit or exchange resets the 90-day period.",
        "Limited lifetime warranty is a different help process. For U.S. warranty assistance, the client takes the product and the original store receipt to their local Good Feet Store. In-store warranty service is free. Coverage is breaking, cracking, or splitting — the product. It is not a promise of a particular pain outcome.",
        "The wearing guide schedule is an example. Individual tolerance varies. No required minimum or maximum wear duration. Do not score exact day-by-day recall. Teach the comfort-based principle and use the guide with the client.",
        "Safety: discontinue use if pain, numbness, or irritation occurs. Specialists are not licensed healthcare providers. Do not diagnose.",
        "Day 3 / 10 / 21 / 30 is an operating commitment from this course. It is not an added refund condition.",
        "Two-minute coaching conversation: What did the client understand? What remained uncertain? Name one behavior. Retry the highest-impact gap. Schedule the next observation.",
      ],
      takeaway: "Refund path and warranty path are not the same store trip. Show the written terms.",
    },
  ],
};
