/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RemarkableRouteImport } from './routes/remarkable'
import { Route as TrainingIndexRouteImport } from './routes/training/index'
import { Route as TrainingTrackRouteImport } from './routes/training/$track'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as TrainingTrackLessonRouteImport } from './routes/training/$track.$lesson'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RemarkableRoute = RemarkableRouteImport.update({
  id: '/remarkable',
  path: '/remarkable',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingIndexRoute = TrainingIndexRouteImport.update({
  id: '/training/',
  path: '/training/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingTrackRoute = TrainingTrackRouteImport.update({
  id: '/training/$track',
  path: '/training/$track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingTrackLessonRoute = TrainingTrackLessonRouteImport.update({
  id: '/$lesson',
  path: '/$lesson',
  getParentRoute: () => TrainingTrackRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/remarkable': typeof RemarkableRoute
  '/training/$track': typeof TrainingTrackRouteWithChildren
  '/training/': typeof TrainingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/training/$track/$lesson': typeof TrainingTrackLessonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/remarkable': typeof RemarkableRoute
  '/training/$track': typeof TrainingTrackRouteWithChildren
  '/training': typeof TrainingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/training/$track/$lesson': typeof TrainingTrackLessonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/remarkable': typeof RemarkableRoute
  '/training/$track': typeof TrainingTrackRouteWithChildren
  '/training/': typeof TrainingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/training/$track/$lesson': typeof TrainingTrackLessonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/how-it-works'
    | '/login'
    | '/remarkable'
    | '/training/$track'
    | '/training/'
    | '/api/auth/$'
    | '/training/$track/$lesson'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/how-it-works'
    | '/login'
    | '/remarkable'
    | '/training/$track'
    | '/training'
    | '/api/auth/$'
    | '/training/$track/$lesson'
  id:
    | '__root__'
    | '/'
    | '/how-it-works'
    | '/login'
    | '/remarkable'
    | '/training/$track'
    | '/training/'
    | '/api/auth/$'
    | '/training/$track/$lesson'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  RemarkableRoute: typeof RemarkableRoute
  TrainingTrackRoute: typeof TrainingTrackRouteWithChildren
  TrainingIndexRoute: typeof TrainingIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remarkable': {
      id: '/remarkable'
      path: '/remarkable'
      fullPath: '/remarkable'
      preLoaderRoute: typeof RemarkableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/': {
      id: '/training/'
      path: '/training'
      fullPath: '/training/'
      preLoaderRoute: typeof TrainingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/$track': {
      id: '/training/$track'
      path: '/training/$track'
      fullPath: '/training/$track'
      preLoaderRoute: typeof TrainingTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/$track/$lesson': {
      id: '/training/$track/$lesson'
      path: '/$lesson'
      fullPath: '/training/$track/$lesson'
      preLoaderRoute: typeof TrainingTrackLessonRouteImport
      parentRoute: typeof TrainingTrackRoute
    }
  }
}

interface TrainingTrackRouteChildren {
  TrainingTrackLessonRoute: typeof TrainingTrackLessonRoute
}

const TrainingTrackRouteChildren: TrainingTrackRouteChildren = {
  TrainingTrackLessonRoute: TrainingTrackLessonRoute,
}

const TrainingTrackRouteWithChildren = TrainingTrackRoute._addFileChildren(
  TrainingTrackRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  RemarkableRoute: RemarkableRoute,
  TrainingTrackRoute: TrainingTrackRouteWithChildren,
  TrainingIndexRoute: TrainingIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
